import { Label } from "./types.ts";
import { v4 as uuidv4 } from "uuid";

const defaultLabels: Label[] = [
  {
    id: uuidv4(),
    name: "PRD",
    bgColor: "#d62828",
    textColor: "#ffffff",
    opacity: 1,
    shape: "block",
    position: "left-top",
    rules: [{"type":"startsWith","value":"akp-"},{"type":"startsWith","value":"wnp-"},{"type":"startsWith","value":"prd-"}],
    isActive: true,
    hoveredOpacity:0.5,
    fadeAfter: 5,
    fontSize: 50,
    scale: 2.45,
  },
  {
    id: uuidv4(),
    name: "EXT",
    bgColor: "#f77f00",
    textColor: "#ffffff",
    opacity: 1,
    shape: "block",
    position: "left-top",
    rules: [{"type":"startsWith","value":"ake-"},{"type":"startsWith","value":"wne-"},{"type":"startsWith","value":"ext-"}],
    isActive: true,
    hoveredOpacity:0.5,
    fadeAfter: 5,
    fontSize: 50,
    scale: 2.45,
  },
  {
    id: uuidv4(),
    name: "CNF",
    bgColor: "#fab005",
    textColor: "#ffffff",
    opacity: 1,
    shape: "block",
    position: "left-top",
    rules: [{"type":"startsWith","value":"akc-"},{"type":"startsWith","value":"wnc-"},{"type":"startsWith","value":"cnf-"}],
    isActive: true,
    hoveredOpacity:0.5,
    fadeAfter: 5,
    fontSize: 50,
    scale: 2.45,
  },
  {
    id: uuidv4(),
    name: "UAT",
    bgColor: "#2A9D8F",
    textColor: "#ffffff",
    opacity: 1,
    shape: "block",
    position: "left-top",
    rules: [{"type":"startsWith","value":"akt-"},{"type":"startsWith","value":"wnt-"},{"type":"startsWith","value":"aku-"},{"type":"startsWith","value":"wnu-"},{"type":"startsWith","value":"uat-"}],
    isActive: true,
    hoveredOpacity:0.5,
    fadeAfter: 5,
    fontSize: 50,
    scale: 2.45,
  },
  {
    id: uuidv4(),
    name: "DEV",
    bgColor: "#287271",
    textColor: "#ffffff",
    opacity: 1,
    shape: "block",
    position: "left-top",
    rules: [{"type":"startsWith","value":"akd-"},{"type":"startsWith","value":"wnd-"},{"type":"startsWith","value":"dev-"},{"type":"startsWith","value":"localhost"}],
    isActive: true,
    hoveredOpacity:0.5,
    fadeAfter: 5,
    fontSize: 50,
    scale: 2.45,
  },
];
export default defaultLabels;